// Taken from glfw3.h
#define RUSH_MOUSE_BUTTON_1      0
#define RUSH_MOUSE_BUTTON_2      1
#define RUSH_MOUSE_BUTTON_3      2
#define RUSH_MOUSE_BUTTON_4      3
#define RUSH_MOUSE_BUTTON_5      4
#define RUSH_MOUSE_BUTTON_6      5
#define RUSH_MOUSE_BUTTON_7      6
#define RUSH_MOUSE_BUTTON_8      7
#define RUSH_MOUSE_BUTTON_LAST   RUSH_MOUSE_BUTTON_8
#define RUSH_MOUSE_BUTTON_LEFT   RUSH_MOUSE_BUTTON_1
#define RUSH_MOUSE_BUTTON_RIGHT  RUSH_MOUSE_BUTTON_2
#define RUSH_MOUSE_BUTTON_MIDDLE RUSH_MOUSE_BUTTON_3